name: learn-github-actions
on:
  release:
    types:
      - published
jobs:
  update-projects:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ secrets.USERNAME }}
      GITHUB_PASSWORD: ${{ secrets.PASSWORD }}
      GITHUB_EMAIL: ${{ secrets.EMAIL }}
      REPO_OWNER: ${{ secrets.USERNAME }}
    steps:
      - name: Install Git and Golang
        run: |
          sudo apt-get install git
          sudo apt install golang-go
      
      - name: Configure Git
        run: |
          echo "github.com:\n- user: $REPO_OWNER\n  oauth_token: ${{ secrets.TOKEN }}\n  protocol: https" > ~/.config/hub
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $REPO_OWNER
        
      - name: Clone the dependant project, configure git repo and create a new update-dependencies branch
        run: |
          git clone https://github.com/$REPO_OWNER/go-release-consume.git
          cd go-release-consume
          git remote set-url origin https://.:${{ secrets.TOKEN }}@github.com/$REPO_OWNER/go-release-consume
          git checkout -b update-dependencies

      - name: Update the dependencies to the lates version
        working-directory: ./go-release-consume
        run: |
          new_version=$(echo "github.com/AxiomSamarth/go-release-event" $(curl -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/$REPO_OWNER/go-release-event/releases/latest | jq '.tag_name' | xargs))
          old_version=$(cat go.mod | grep github.com/$REPO_OWNER/go-release-event | xargs)
          sed -i -- 's#'"$old_version"'#'"$new_version"'#g' go.mod
          go mod vendor
          go mod tidy

      - name: Push the updates and raise a pull request
        working-directory: ./go-release-consume
        run: |
          git add *
          git commit -m "automated vendoring of latest release of go-release-event"
          git push  --force --quiet https://$REPO_OWNER:${{ secrets.TOKEN }}@github.com/$REPO_OWNER/go-release-consume update-dependencies:update-dependencies
          hub pull-request --base main --head update-dependencies -m "Automated Vendoring of latest release of go-release-event\n\n_Release notes_\n```\ngo-releave-event version $new_version has been vendored.\n```"
                    
        


          
