name: learn-github-actions
on: [release]
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
            EMAIL: ${{ secrets.email }}
            USERNAME: ${{ secrets.username }}
        run: |
          # install git
          sudo apt-get install git
          sudo apt install golang-go
          
          echo $GITHUB_TOKEN

          # get the latest release version of the repository
          new_version=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/AxiomSamarth/go-release-event/releases/latest | jq '.tag_name')
          echo "New version after curl" $new_version

          new_version=$(echo $new_version | xargs)
          echo "New version after trim" $new_version
          
          new_version=$(echo "github.com/AxiomSamarth/go-release-event" $new_version)
          echo "New version final" $new_version
          
          # clone the dependant repository
          git clone https://github.com/AxiomSamarth/go-release-consume

          # navigate to dependant repository
          cd go-release-consume
          old_version=$(cat go.mod | grep github.com/AxiomSamarth/go-release-event | xargs)

          echo "Old version:$old_version New version:$new_version"

          # update the go.mod file of dependant project to the latest release version of this project
          git checkout -b update-dependencies
          sed -i -- 's#'"$old_version"'#'"$new_version"'#g' go.mod
          
          cat go.mod

          go mod vendor
          go mod tidy

          # configure github.com/AxiomSamarth/go-release-event

          git config --global user.email deyagondsamarth@gmail.com
          git config --global user.name AxiomSamarth

          git add *
          git commit -m "automated vendoring of latest release of go-release-event"
          git push origin update-dependencies
          hub pull-request --base main --head update-dependencies -m "update release-event dependencies"
        


          
