name: learn-github-actions
on: [release]
jobs:
  check-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ secrets.USERNAME }}
      GITHUB_PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Vendor the dependecies into referring projects
        uses: actions/checkout@main
        run: sh ./build.sh
          
        


          
