name: learn-github-actions
on:
  release:
    types:
      - published
jobs:
  update-projects:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ secrets.USERNAME }}
      GITHUB_PASSWORD: ${{ secrets.TOKEN }}
      GITHUB_EMAIL: ${{ secrets.EMAIL }}
      SRC_REPO_OWNER: ${{ secrets.USERNAME }}
      SRC_REPO_NAME: go-release-event
    steps:
      - name: Install Git and Golang
        run: |
          sudo apt-get install git
          sudo apt install golang-go
      
      - name: Configure Git
        run: |
          echo "github.com:\n- user: $GITHUB_USER\n  oauth_token: ${{ secrets.TOKEN }}\n  protocol: https" > ~/.config/hub
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_USER
        
      - name: Clone the dependant project, configure git repo and create a new update-dependencies branch
        uses: AxiomSamarth/go-vendor-action@main
        with:
          destination_repo_owner: AxiomSamarth
          destination_repo_name: go-release-consume        
