name: learn-github-actions
on: [release]
jobs:
  check-version:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      GITHUB_USER: ${{ secrets.USERNAME }}
      GITHUB_PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v2
        env:
          REPO: AxiomSamarth/go-release-consume
          REPO_PATH: go-release-consume
        with:
          fetch-depth: 0
          repository: "${{ env.REPO }}"
          path: ${{ env.REPO_PATH }}
      - name: Setup versions
        run: |
          sudo apt install golang-go

          # get the latest release version of the repository
          new_version=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/AxiomSamarth/go-release-event/releases/latest | jq '.tag_name')
          new_version=$(echo $new_version | xargs)
          new_version=$(echo "github.com/AxiomSamarth/go-release-event" $new_version)
          
          # clone the dependant repository
          git clone https://github.com/$REPO.git

          # navigate to dependant repository
          cd $REPO_PATH

          git remote set-url origin https://.:${{ secrets.TOKEN }}@github.com/$REPO
          echo "github.com:\n- user: AxiomSamarth\n  oauth_token: ${{ secrets.TOKEN }}\n  protocol: https" > ~/.config/hub

          old_version=$(cat go.mod | grep github.com/AxiomSamarth/go-release-event | xargs)

          echo "Old version:$old_version New version:$new_version"

          # update the go.mod file of dependant project to the latest release version of this project
          git checkout -b update-dependencies
          sed -i -- 's#'"$old_version"'#'"$new_version"'#g' go.mod

          go mod vendor
          go mod tidy

          # configure github.com/AxiomSamarth/go-release-event

          git config --global user.email deyagondsamarth@gmail.com
          git config --global user.name AxiomSamarth

          git add *
          git commit -m "automated vendoring of latest release of go-release-event"
          git push  --force --quiet https://AxiomSamarth:${{ secrets.TOKEN }}@github.com/$REPO update-dependencies:update-dependencies
          
          hub pull-request --base main --head update-dependencies -m "update release-event dependencies"